# Generated by Django 5.0.6 on 2024-06-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_view_count', models.IntegerField(default=0)),
                ('about_me_view_count', models.IntegerField(default=0)),
                ('education_view_count', models.IntegerField(default=0)),
                ('skills_view_count', models.IntegerField(default=0)),
                ('contact_view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
