# Generated by Django 5.0.6 on 2024-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
