# Generated by Django 5.1.2 on 2024-12-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='sub_title',
        ),
    ]
