# Generated by Django 5.0.6 on 2024-08-27 18:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_about_me_contact_education_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
