# Generated by Django 5.1.2 on 2025-07-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_skills_sub_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_me',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
