# Generated by Django 5.0.6 on 2024-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_education_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedln',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
